// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8QK-n7a7osC5stv3XAc1jtPk7P52rVo',
    appId: '1:881384185995:web:6dc87e711ebc201509348e',
    messagingSenderId: '881384185995',
    projectId: 'my-project-1550647865517',
    authDomain: 'my-project-1550647865517.firebaseapp.com',
    databaseURL: 'https://my-project-1550647865517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-project-1550647865517.appspot.com',
    measurementId: 'G-PC84XXTD6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx-XSpvkFcQbAnDdwv5iBn01Q5j3-Aogw',
    appId: '1:881384185995:android:f13d543a6e816c8009348e',
    messagingSenderId: '881384185995',
    projectId: 'my-project-1550647865517',
    databaseURL: 'https://my-project-1550647865517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-project-1550647865517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07lyc7nHQEouopaYKzn6NCyVQPTgtOVU',
    appId: '1:881384185995:ios:47665a8bd2c2d06309348e',
    messagingSenderId: '881384185995',
    projectId: 'my-project-1550647865517',
    databaseURL: 'https://my-project-1550647865517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-project-1550647865517.appspot.com',
    iosBundleId: 'com.example.parkassist',
  );
}
